package exception;

public enum AMLSyntaxExceptions {
	ERR_KEY_ALREADY_EXISTS,
	ERR_SECTION_START_MISSING,
	ERR_SECTION_STATES_MISSING,
	ERR_SECTION_TRANSITIONS_MISSING,
	ERR_UNEXPECTED_IDENTIFIER,
	ERR_UNKNOWN_TYPE,
	ERR_UNKNOWN_STATE
}
